version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: ${container_name}
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./elt/init_db:/docker-entrypoint-initdb.d
